### ISSUE TITLE
incompatibility with facebook pixels 1.7.5.1

### ISSUE THREAD

**Issue by sanctusmob** [L3o-pold/prestashopamp#12] opened 2019-04-02 10:09 UTC
The problem #6  still exists in Prestashop 1.7.5.1
If i disable fb pixel, amp module is working ok.
I also check the exceptions in header hook and they are there correctly.

The error i got

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method AmpProductModuleFrontController::getTemplateVarProduct() in /var/www/vhosts/XXX/httpdocs/modules/pspixel/pspixel.php:233\nStack trace:\n#0 /var/www/vhosts/XXX/httpdocs/classes/Hook.php(966): Pspixel->hookHeader(Array)\n#1 /var/www/vhosts/XXX/httpdocs/classes/Hook.php(355): HookCore::coreCallHook(Object(Pspixel), 'hookHeader', Array)\n#2 /var/www/vhosts/XXX/httpdocs/classes/Hook.php(903): HookCore::callHookOn(Object(Pspixel), 'displayHeader', Array)\n#3 /var/www/vhosts/XXX/httpdocs/classes/controller/FrontController.php(555): HookCore::exec('displayHeader')\n#4 /var/www/vhosts/XXX/httpdocs/classes/controller/ModuleFrontController.php(77): FrontControllerCore->initContent()\n#5 /var/www/vhosts/XXX/httpdocs/modules/amp/controllers/front/product.php(190): ModuleFrontControllerCore->initContent()\n#6 /var/www/vhosts/XXX/httpdocs/classes/controller/Controller.php(281): AmpProdu...\n`

**Comment by L3o-pold** [comment] 2019-07-28 10:37
AMP works with the FB Pixel module, **but** FB Pixel module doesn't work with the AMP Module.
I'll check if we could fix that on our side.

**Comment by L3o-pold** [comment] 2019-07-28 11:29
Are you talking about this module https://addons.prestashop.com/fr/produits-sur-facebook-reseaux-sociaux/27646-pixel-facebook-officiel-17.html

If so I can't test it because of the price. Please provide me a copy of this module to debug.

**Comment by L3o-pold** [comment] 2019-07-28 11:33
Close as a duplicate of #6. Please reopen that issue if you could provide me the module to check it out.

**Closed as completed by L3o-pold** 2019-07-28 11:33 UTC
